#!/bin/bash

VM=$1
HOST=$2
VG=lvm
BLOCKSIZE=4194304

echo "Moving ${VM} to ${HOST}. Ok?"
read

SOURCE_LV=/dev/${VG}/${VM}
if [ "${SOURCE_LV}" == "" ] ; then
  echo "No source logical volume detected."
  exit
fi

BLOCKS=`lvdisplay ${SOURCE_LV} | grep "Current LE" | cut -b26-`
SIZE=`echo "${BLOCKSIZE} * ${BLOCKS}" | bc`
echo "- Source volumne ${SOURCE_LV} has ${BLOCKS} blocks"

echo "* Check destination host"
CHECK=`ssh root@${HOST} "if [ -e /dev/${VG}/${VM} ] ; then echo \"- Logical volumne already exists on destination host\" ; fi"`
if [ "${CHECK}" != "" ] ; then
  echo ${CHECK}
  exit 1
fi
CHECK=`ssh root@${HOST} "if [ -e /etc/libvirt/qemu/${VM}.xml -o -e /etc/libvirt/qemu/autostart/${VM}.xml ] ; then echo \"- VM configuration already exists on destination host\" ; fi"`
if [ "${CHECK}" != "" ] ; then
  echo ${CHECK}
  exit 1
fi

echo "- VM does not exist on destinaton host"

echo "* Creating snapshot volume ${SNAPSHOT_LV}"
SNAPSHOT_LV=/dev/${VG}/${VM}_vm_move2host
lvcreate -n${VM}_vm_move2host -s -L1G ${SOURCE_LV}

echo "* Copying VM configuration"
tar cf - /etc/libvirt/qemu/${VM}.xml /etc/libvirt/qemu/autostart/${VM}.xml | ssh root@${HOST} "cd / ; tar xf -"
ssh root@${HOST} "virsh define /etc/libvirt/qemu/${VM}.xml"

echo "* Creating destination volume"
ssh root@${HOST} "lvcreate -l${BLOCKS} -n${VM} ${VG_PSEUDO}"
DEST_LV=/dev/${VG_PSEUDO}/${VM}

echo "* Copying snapshot"
dd bs=1M if=${SNAPSHOT_LV} | pv -s${SIZE} -B1M | ssh -C root@${HOST} "dd bs=1M of=${DEST_LV}"

echo "* Powering down VM"
virsh shutdown ${VM}

echo "* Transfering filesystem changes"
lvs ${SNAPSHOT_LV}
lvmsync ${SNAPSHOT_LV} ${HOST}:${DEST_LV}

echo "* Starting VM on ${HOST}"
ssh root@${HOST} "virsh start ${VM}"
